package main;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Locale;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import jdialg.ModificarPerfil;
import jinternal.ListadoAulas;
import jinternal.ListadoCarreras;
import jinternal.ListadoCursosCicloImpartir;
import jinternal.ListadoDeCiclos;
import jinternal.ListadoDeCursos;
import jinternal.ListadoEdificios;
import jinternal.ListadoFacultad;
import jinternal.ListadoUsuarios;
import jinternal.RegistrarAulas;
import jinternal.RegistrarCarrera;
import jinternal.RegistrarCiclos;
import jinternal.RegistrarCursos;
import jinternal.RegistrarCursosCicloImpartir;
import jinternal.RegistrarEdificio;
import jinternal.RegistrarFacultad;
import jinternal.RegistrarUsuario;

/**
 *
 * @author santoslopeztzoy
 */
public class MenuPrincipalJFrameAdministrador extends javax.swing.JFrame {
    
    private static MenuPrincipalJFrameAdministrador instancia;
    public static MenuPrincipalJFrameAdministrador getInstancia(){
        if(instancia==null){
            instancia=new MenuPrincipalJFrameAdministrador();
        }
        return instancia;
    }
    
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    
    // obtener ancho y alto
    int ancho = screenSize.width;
    int alto = screenSize.height;
    int dimensionRestar = 300;
    
    /**
     * Creates new form MenuPrincipalJFrame
     */
    public MenuPrincipalJFrameAdministrador() {
        initComponents();
        this.setSize(ancho-dimensionRestar,alto-dimensionRestar);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        jLabelTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblImagenFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemRegistrarUsuarios = new javax.swing.JMenuItem();
        jMenuItemListarUsuarios = new javax.swing.JMenuItem();
        jMenuFacultad = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemListarFacultad = new javax.swing.JMenuItem();
        jMenuCarreras = new javax.swing.JMenu();
        jMenuItemRegistrarCarreras = new javax.swing.JMenuItem();
        jMenuItemListarCarreras = new javax.swing.JMenuItem();
        jMenuEdificios = new javax.swing.JMenu();
        jMenuItemRegistrarEdificios = new javax.swing.JMenuItem();
        jMenuItemListadoEdificios = new javax.swing.JMenuItem();
        jMenuAulas = new javax.swing.JMenu();
        jMenuItemRegistrarAulas = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuCiclos = new javax.swing.JMenu();
        jMenuItemRegistrarCiclos = new javax.swing.JMenuItem();
        jMenuItemListadoDeCiclos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemRegistrarCursos = new javax.swing.JMenuItem();
        jMenuItemListadoDeCursos = new javax.swing.JMenuItem();
        jMenuCursosCicloImpartir = new javax.swing.JMenu();
        jMenuItemRegistrarCursosCicloImpartir = new javax.swing.JMenuItem();
        jMenuItemListadoCursosCiclos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemActualizarPerfil = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuHorarioClaseProfesor = new javax.swing.JMenu();
        jMenuItemRegistrarHorarioClaseProfesor = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabelTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 28)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 51, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("SISTEMA EDUCATIVO");

        lblUsuario.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel1.setText("Bienvenido:");

        lblImagenFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/university.png"))); // NOI18N
        lblImagenFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        escritorio.setLayer(jLabelTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblImagenFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblImagenFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImagenFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        jMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/user-5.png"))); // NOI18N
        jMenuUsuarios.setText("Usuarios");
        jMenuUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItemRegistrarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/incorporation.png"))); // NOI18N
        jMenuItemRegistrarUsuarios.setText("Registrar");
        jMenuItemRegistrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarUsuariosActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemRegistrarUsuarios);

        jMenuItemListarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/male-student.png"))); // NOI18N
        jMenuItemListarUsuarios.setText("Lista estudiantes");
        jMenuItemListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarUsuariosActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemListarUsuarios);

        jMenuBar1.add(jMenuUsuarios);

        jMenuFacultad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/education.png"))); // NOI18N
        jMenuFacultad.setText("Facultad");
        jMenuFacultad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuFacultad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/plus.png"))); // NOI18N
        jMenuItem1.setText("Registrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuFacultad.add(jMenuItem1);

        jMenuItemListarFacultad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/list.png"))); // NOI18N
        jMenuItemListarFacultad.setText("Listar facultades");
        jMenuItemListarFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarFacultadActionPerformed(evt);
            }
        });
        jMenuFacultad.add(jMenuItemListarFacultad);

        jMenuBar1.add(jMenuFacultad);

        jMenuCarreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/graduation-ceremony.png"))); // NOI18N
        jMenuCarreras.setText("Carreras");
        jMenuCarreras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuCarreras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItemRegistrarCarreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/plus.png"))); // NOI18N
        jMenuItemRegistrarCarreras.setText("Registrar");
        jMenuItemRegistrarCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarCarrerasActionPerformed(evt);
            }
        });
        jMenuCarreras.add(jMenuItemRegistrarCarreras);

        jMenuItemListarCarreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/graduated.png"))); // NOI18N
        jMenuItemListarCarreras.setText("Listado de carreras");
        jMenuItemListarCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarCarrerasActionPerformed(evt);
            }
        });
        jMenuCarreras.add(jMenuItemListarCarreras);

        jMenuBar1.add(jMenuCarreras);

        jMenuEdificios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/building.png"))); // NOI18N
        jMenuEdificios.setText("Edificios");
        jMenuEdificios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuEdificios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItemRegistrarEdificios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/plus.png"))); // NOI18N
        jMenuItemRegistrarEdificios.setText("Registrar");
        jMenuItemRegistrarEdificios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarEdificiosActionPerformed(evt);
            }
        });
        jMenuEdificios.add(jMenuItemRegistrarEdificios);

        jMenuItemListadoEdificios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/skyscraper.png"))); // NOI18N
        jMenuItemListadoEdificios.setText("Listado de edificios");
        jMenuItemListadoEdificios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoEdificiosActionPerformed(evt);
            }
        });
        jMenuEdificios.add(jMenuItemListadoEdificios);

        jMenuBar1.add(jMenuEdificios);

        jMenuAulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/classroom-2.png"))); // NOI18N
        jMenuAulas.setText("Aulas");
        jMenuAulas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuAulas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItemRegistrarAulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/plus.png"))); // NOI18N
        jMenuItemRegistrarAulas.setText("Registrar aulas");
        jMenuItemRegistrarAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarAulasActionPerformed(evt);
            }
        });
        jMenuAulas.add(jMenuItemRegistrarAulas);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/classroom.png"))); // NOI18N
        jMenuItem3.setText("Listado de aulas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuAulas.add(jMenuItem3);

        jMenuBar1.add(jMenuAulas);

        jMenuCiclos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/calendar-2.png"))); // NOI18N
        jMenuCiclos.setText("Ciclos");
        jMenuCiclos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuCiclos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItemRegistrarCiclos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/plus.png"))); // NOI18N
        jMenuItemRegistrarCiclos.setText("Registrar ciclos");
        jMenuItemRegistrarCiclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarCiclosActionPerformed(evt);
            }
        });
        jMenuCiclos.add(jMenuItemRegistrarCiclos);

        jMenuItemListadoDeCiclos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/calendar.png"))); // NOI18N
        jMenuItemListadoDeCiclos.setText("Listado de ciclos");
        jMenuItemListadoDeCiclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoDeCiclosActionPerformed(evt);
            }
        });
        jMenuCiclos.add(jMenuItemListadoDeCiclos);

        jMenuBar1.add(jMenuCiclos);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/online-education.png"))); // NOI18N
        jMenu4.setText("Cursos");
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItemRegistrarCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/plus.png"))); // NOI18N
        jMenuItemRegistrarCursos.setText("Registrar cursos");
        jMenuItemRegistrarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarCursosActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemRegistrarCursos);

        jMenuItemListadoDeCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/courses.png"))); // NOI18N
        jMenuItemListadoDeCursos.setText("Listado de cursos");
        jMenuItemListadoDeCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoDeCursosActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemListadoDeCursos);

        jMenuBar1.add(jMenu4);

        jMenuCursosCicloImpartir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/teaching.png"))); // NOI18N
        jMenuCursosCicloImpartir.setText("Cursos ciclos impartir");
        jMenuCursosCicloImpartir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuCursosCicloImpartir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItemRegistrarCursosCicloImpartir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/plus.png"))); // NOI18N
        jMenuItemRegistrarCursosCicloImpartir.setText("Registrar");
        jMenuItemRegistrarCursosCicloImpartir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarCursosCicloImpartirActionPerformed(evt);
            }
        });
        jMenuCursosCicloImpartir.add(jMenuItemRegistrarCursosCicloImpartir);

        jMenuItemListadoCursosCiclos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/note.png"))); // NOI18N
        jMenuItemListadoCursosCiclos.setText("Listado");
        jMenuItemListadoCursosCiclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoCursosCiclosActionPerformed(evt);
            }
        });
        jMenuCursosCicloImpartir.add(jMenuItemListadoCursosCiclos);

        jMenuBar1.add(jMenuCursosCicloImpartir);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/user-6.png"))); // NOI18N
        jMenu1.setText("Perfil");
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItemActualizarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/gear.png"))); // NOI18N
        jMenuItemActualizarPerfil.setText("Actualizar perfil");
        jMenuItemActualizarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizarPerfilActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemActualizarPerfil);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/logout.png"))); // NOI18N
        jMenuItem2.setText("Cerrar sesión");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenuHorarioClaseProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/school.png"))); // NOI18N
        jMenuHorarioClaseProfesor.setText("Horario clase profesor");
        jMenuHorarioClaseProfesor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuHorarioClaseProfesor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItemRegistrarHorarioClaseProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/plus.png"))); // NOI18N
        jMenuItemRegistrarHorarioClaseProfesor.setText("Registrar");
        jMenuItemRegistrarHorarioClaseProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarHorarioClaseProfesorActionPerformed(evt);
            }
        });
        jMenuHorarioClaseProfesor.add(jMenuItemRegistrarHorarioClaseProfesor);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-admin/clipboard.png"))); // NOI18N
        jMenuItem4.setText("Listado de clases profesor");
        jMenuHorarioClaseProfesor.add(jMenuItem4);

        jMenuBar1.add(jMenuHorarioClaseProfesor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRegistrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarUsuariosActionPerformed
        // TODO add your handling code here:
        if(!escritorio.isAncestorOf(RegistrarUsuario.getInstancia())){
            escritorio.add(RegistrarUsuario.getInstancia());
            RegistrarUsuario.getInstancia().setVisible(true);
        }else{
            escritorio.setSelectedFrame(RegistrarUsuario.getInstancia());
        }
    }//GEN-LAST:event_jMenuItemRegistrarUsuariosActionPerformed

    private void jMenuItemListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarUsuariosActionPerformed
        // TODO add your handling code here:
        
        if(!escritorio.isAncestorOf(ListadoUsuarios.getInstancia())){
            escritorio.add(ListadoUsuarios.getInstancia());
            ListadoUsuarios.getInstancia().setVisible(true);
        }else{
            escritorio.setSelectedFrame(ListadoUsuarios.getInstancia());
        }
    }//GEN-LAST:event_jMenuItemListarUsuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(!escritorio.isAncestorOf(RegistrarFacultad.getInstancia())){
            escritorio.add(RegistrarFacultad.getInstancia());
            RegistrarFacultad.getInstancia().setVisible(true);
        }else{
            escritorio.setSelectedFrame(RegistrarFacultad.getInstancia());
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemListarFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarFacultadActionPerformed
        // TODO add your handling code here:
       
        ListadoFacultad listado = new ListadoFacultad();
        if(!escritorio.isAncestorOf(listado)){
            escritorio.add(listado);
            listado.setVisible(true);
        }else{
            escritorio.setSelectedFrame(listado);
        }
        
    }//GEN-LAST:event_jMenuItemListarFacultadActionPerformed

    private void jMenuItemListarCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarCarrerasActionPerformed
        // TODO add your handling code here:        
        ListadoCarreras listado = new ListadoCarreras();
        if(!escritorio.isAncestorOf(listado)){
            escritorio.add(listado);
            listado.setVisible(true);
        }else{
            escritorio.setSelectedFrame(listado);
        }
        
    }//GEN-LAST:event_jMenuItemListarCarrerasActionPerformed

    private void jMenuItemRegistrarCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarCarrerasActionPerformed
        // TODO add your handling code here:
        RegistrarCarrera reg = new RegistrarCarrera();
        
        if(!escritorio.isAncestorOf(RegistrarCarrera.getInstancia())){
            escritorio.add(reg);
            reg.setVisible(true);
        }else{
            escritorio.setSelectedFrame(reg);
        }
        
    }//GEN-LAST:event_jMenuItemRegistrarCarrerasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int confirmarCerrarSesion = JOptionPane.showConfirmDialog(null,"¿Confirmar cierre del programa?","Mensaje",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(confirmarCerrarSesion==JOptionPane.YES_OPTION){
            System.exit(0);
        }
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemActualizarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActualizarPerfilActionPerformed
        // TODO add your handling code here:
        //ModificarPerfil m = new ModificarPerfil(this,true);
        ModificarPerfil.getInstancia().setVisible(true);
        String usuario = lblUsuario.getText();
        ModificarPerfil.getInstancia().setNombres(usuario);
        
    }//GEN-LAST:event_jMenuItemActualizarPerfilActionPerformed

    private void jMenuItemListadoEdificiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoEdificiosActionPerformed
        // TODO add your handling code here:
        if(!escritorio.isAncestorOf(ListadoEdificios.getInstancia())){
            escritorio.add(ListadoEdificios.getInstancia());
            ListadoEdificios.getInstancia().setVisible(true);
        }else{
            escritorio.setSelectedFrame(ListadoEdificios.getInstancia());
        }
    }//GEN-LAST:event_jMenuItemListadoEdificiosActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        if(!escritorio.isAncestorOf(ListadoAulas.getInstancia())){
            escritorio.add(ListadoAulas.getInstancia());
            ListadoAulas.getInstancia().setVisible(true);
        }else{
            escritorio.setSelectedFrame(ListadoAulas.getInstancia());
        }
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItemListadoDeCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoDeCiclosActionPerformed
        // TODO add your handling code here:
        if(!escritorio.isAncestorOf(ListadoDeCiclos.getInstancia())){
            escritorio.add(ListadoDeCiclos.getInstancia());
            ListadoDeCiclos.getInstancia().setVisible(true);
            
        }else{
            escritorio.setSelectedFrame(ListadoDeCiclos.getInstancia());
        }
    }//GEN-LAST:event_jMenuItemListadoDeCiclosActionPerformed

    private void jMenuItemRegistrarCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarCiclosActionPerformed
        // TODO add your handling code here:
        if(!escritorio.isAncestorOf(RegistrarCiclos.getInstancia())){
            escritorio.add(RegistrarCiclos.getInstancia());
            RegistrarCiclos.getInstancia().setVisible(true);
        }else{
            escritorio.setSelectedFrame(RegistrarCiclos.getInstancia());
        }
    }//GEN-LAST:event_jMenuItemRegistrarCiclosActionPerformed

    private void jMenuItemListadoDeCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoDeCursosActionPerformed
        // TODO add your handling code here:
        
        if(!escritorio.isAncestorOf(ListadoDeCursos.getInstancia())){
            escritorio.add(ListadoDeCursos.getInstancia());
            
            ListadoDeCursos.getInstancia().setVisible(true);
        }else{
            escritorio.setSelectedFrame(ListadoDeCursos.getInstancia());
        }
    }//GEN-LAST:event_jMenuItemListadoDeCursosActionPerformed

    private void jMenuItemRegistrarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarCursosActionPerformed
        // TODO add your handling code here:
        
        RegistrarCursos registrar = new RegistrarCursos();
        if(!escritorio.isAncestorOf(registrar)){
           escritorio.add(registrar);
           registrar.setVisible(true);
        }else{
            escritorio.setSelectedFrame(registrar);
        }
    }//GEN-LAST:event_jMenuItemRegistrarCursosActionPerformed

    private void jMenuItemRegistrarAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarAulasActionPerformed
        // TODO add your handling code here:
        RegistrarAulas registrar = new RegistrarAulas();
        if(!escritorio.isAncestorOf(registrar)){
           escritorio.add(registrar);
           registrar.setVisible(true);
        }else{
            escritorio.setSelectedFrame(registrar);
        }        
    }//GEN-LAST:event_jMenuItemRegistrarAulasActionPerformed

    private void jMenuItemRegistrarEdificiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarEdificiosActionPerformed
        // TODO add your handling code here:
        RegistrarEdificio registrarEdificio = new RegistrarEdificio();
        if(!escritorio.isAncestorOf(registrarEdificio)){
            escritorio.add(registrarEdificio);
            registrarEdificio.setVisible(true);
        }else{
            escritorio.setSelectedFrame(registrarEdificio);
        }
        
    }//GEN-LAST:event_jMenuItemRegistrarEdificiosActionPerformed

    private void jMenuItemRegistrarCursosCicloImpartirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarCursosCicloImpartirActionPerformed
        // TODO add your handling code here:
        RegistrarCursosCicloImpartir reg = new RegistrarCursosCicloImpartir();
        
        if(!escritorio.isAncestorOf(reg)){
            escritorio.add(reg);
            reg.setVisible(true);
        }else{
            escritorio.setSelectedFrame(reg);
        }
        
    }//GEN-LAST:event_jMenuItemRegistrarCursosCicloImpartirActionPerformed

    private void jMenuItemListadoCursosCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoCursosCiclosActionPerformed
        // TODO add your handling code here:
        ListadoCursosCicloImpartir list = new ListadoCursosCicloImpartir();
        
        if(!escritorio.isAncestorOf(list)){
            escritorio.add(list);
            list.setVisible(true);
        }else{
            escritorio.setSelectedFrame(list);
        }
    }//GEN-LAST:event_jMenuItemListadoCursosCiclosActionPerformed

    private void jMenuItemRegistrarHorarioClaseProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarHorarioClaseProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRegistrarHorarioClaseProfesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalJFrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalJFrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalJFrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalJFrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalJFrameAdministrador().setVisible(true);
            }
        });
    }
    
    public JLabel getUsuario(){
        return lblUsuario;
    }
    
    public void setUsuario(String usuario){
        lblUsuario.setText(usuario);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuAulas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuCarreras;
    private javax.swing.JMenu jMenuCiclos;
    private javax.swing.JMenu jMenuCursosCicloImpartir;
    private javax.swing.JMenu jMenuEdificios;
    private javax.swing.JMenu jMenuFacultad;
    private javax.swing.JMenu jMenuHorarioClaseProfesor;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemActualizarPerfil;
    private javax.swing.JMenuItem jMenuItemListadoCursosCiclos;
    private javax.swing.JMenuItem jMenuItemListadoDeCiclos;
    private javax.swing.JMenuItem jMenuItemListadoDeCursos;
    private javax.swing.JMenuItem jMenuItemListadoEdificios;
    private javax.swing.JMenuItem jMenuItemListarCarreras;
    private javax.swing.JMenuItem jMenuItemListarFacultad;
    private javax.swing.JMenuItem jMenuItemListarUsuarios;
    private javax.swing.JMenuItem jMenuItemRegistrarAulas;
    private javax.swing.JMenuItem jMenuItemRegistrarCarreras;
    private javax.swing.JMenuItem jMenuItemRegistrarCiclos;
    private javax.swing.JMenuItem jMenuItemRegistrarCursos;
    private javax.swing.JMenuItem jMenuItemRegistrarCursosCicloImpartir;
    private javax.swing.JMenuItem jMenuItemRegistrarEdificios;
    private javax.swing.JMenuItem jMenuItemRegistrarHorarioClaseProfesor;
    private javax.swing.JMenuItem jMenuItemRegistrarUsuarios;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagenFondo;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
