/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package jinternal;

import db.Conexion;
import bean.Carreras;
import bean.LlenarComboBox;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import manejador.ManejadorDeCarreras;

/**
 *
 * @author santoslopeztzoy
 */
public class RegistrarCarrera extends javax.swing.JInternalFrame {
    
    private Carreras carrera=new Carreras();

    private static RegistrarCarrera instancia;
    
    public static RegistrarCarrera getInstancia(){
        if(instancia==null){
            instancia=new RegistrarCarrera();
        }
        return instancia;
    }
    
    
    public void llenarComboBox(){
        String consulta="SELECT DISTINCT f.idFacultad,f.nombre FROM Carreras AS c INNER JOIN Facultad AS f ON c.idFacultad=c.idFacultad;";
        // no hace nada debido a que no es relevante para la consulta que estamos haciendo
        Object[] params={};
        LlenarComboBox.getInstancia().tipoCuenta(cboFacultad,consulta,params,"idFacultad","nombre");
    }
    
    /**
     * Creates new form RegistrarCarrera
     */
    public RegistrarCarrera() {
        initComponents();
        setClosable(true);
        llenarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedorPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblFacultad = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        cboFacultad = new javax.swing.JComboBox<>();

        setTitle("Registrar carrera");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar carrera");

        lblNombre.setText("Nombre");

        lblFacultad.setText("Facultad");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cboFacultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelContenedorPrincipalLayout = new javax.swing.GroupLayout(jPanelContenedorPrincipal);
        jPanelContenedorPrincipal.setLayout(jPanelContenedorPrincipalLayout);
        jPanelContenedorPrincipalLayout.setHorizontalGroup(
            jPanelContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtNombre)
            .addComponent(lblFacultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cboFacultad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelContenedorPrincipalLayout.setVerticalGroup(
            jPanelContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nombreCarrera = txtNombre.getText();
        
        int confirmarGuardar = JOptionPane.showConfirmDialog(null,"¿Deseas guardar los datos?","Mensaje",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        
        if(confirmarGuardar==JOptionPane.YES_OPTION){
           
            /*carrera = ManejadorDeCarreras.getInstancia().verificarCarreras(nombreCarrera);
            
            if(carrera!=null){

                JOptionPane.showMessageDialog(null, "Error, nombre de carrera ya existe","Mensaje",JOptionPane.ERROR_MESSAGE);
            }else{
                String sentencia="INSERT INTO Carreras(nombre,idFacultad) VALUES(?,?)"; 

                // necesario para recuperar el ID del combobox seleccionado
                LlenarComboBox combobox = (LlenarComboBox)cboFacultad.getSelectedItem();
                
                int idFacultad = combobox.getId();

                Object[] params = {nombreCarrera,idFacultad};
                Conexion.getInstancia().ejecutarSentencia(sentencia, params);

                JOptionPane.showMessageDialog(null, "Registro exitoso","Mensaje",JOptionPane.INFORMATION_MESSAGE);   
            }*/
            LlenarComboBox combobox = (LlenarComboBox)cboFacultad.getSelectedItem();
            int idFacultad = combobox.getId();
            
            String sentencia = "CALL agregarCarreras(?,?)";
            Object[] params={nombreCarrera,idFacultad};
            ResultSet consulta = Conexion.getInstancia().hacerConsulta(sentencia,params);
            
            try{
                if (consulta!=null){

                    if(consulta.next()){
                        String mensajeObtenido = consulta.getString("mensaje");
  
                        if(mensajeObtenido.equals("enuso")){
                            
                            JOptionPane.showMessageDialog(null, "Error, nombre de carrera en uso.","Mensaje",JOptionPane.ERROR_MESSAGE);   
                            
                        }else if(mensajeObtenido.equals("registrado")){
                            JOptionPane.showMessageDialog(null, "Registro exitoso","Mensaje",JOptionPane.INFORMATION_MESSAGE);   
                            txtNombre.setText("");
                            
                        }else{
                            
                        }
                    }
                }                
            }catch(Exception ex){
                ex.printStackTrace();
            }            
        }
              
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboFacultad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelContenedorPrincipal;
    private javax.swing.JLabel lblFacultad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
