/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package jinternal;

import bean.LlenarComboBox;
import db.Conexion;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author santoslopeztzoy
 */
public class RegistrarAulas extends javax.swing.JInternalFrame {

    

    
    /**
     * Creates new form RegistrarAulas
     */
    public RegistrarAulas() {
        initComponents();
        llenarCombobox();
    }

    
    public void llenarCombobox(){
        String consulta = "SELECT idEdificio,nombreEdificio FROM Edificio";

        Object[] params = {};
        LlenarComboBox.getInstancia().tipoCuenta(cboEdificio, consulta, params,"idEdificio","nombreEdificio");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSalon = new javax.swing.JLabel();
        txtNombreSalon = new javax.swing.JTextField();
        lblEdificio = new javax.swing.JLabel();
        cboEdificio = new javax.swing.JComboBox<>();
        lblNivel = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();
        btnRegistrarAulas = new javax.swing.JButton();

        setClosable(true);

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registrar aulas");

        lblSalon.setText("Nombre de salón");

        lblEdificio.setText("Edificio");

        cboEdificio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNivel.setText("Nivel");

        btnRegistrarAulas.setText("Registrar aula");
        btnRegistrarAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAulasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSalon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtNombreSalon)
            .addComponent(lblEdificio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cboEdificio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtNivel)
            .addComponent(btnRegistrarAulas, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAulasActionPerformed
        // TODO add your handling code here:
        /*String nombreSalon = txtNombreSalon.getText();
        
        String nivel = txtNivel.getText();*/
        String nombreSalon = txtNombreSalon.getText();
        
        String nivel = txtNivel.getText();
        LlenarComboBox combobox = (LlenarComboBox)cboEdificio.getSelectedItem();
        
        
        /*if ((nombreSalon.length()<=0) || (nivel.length()<=0) ){
            JOptionPane.showMessageDialog(null, "Error, debe ingresar un nombre de la carrera","Mensaje",JOptionPane.ERROR_MESSAGE);
            
            return;
        }*/

        
        int confirmarGuardar = JOptionPane.showConfirmDialog(null,"¿Deseas guardar los datos?","Mensaje",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(confirmarGuardar==JOptionPane.YES_OPTION){
            if (combobox==null){
                
                JOptionPane.showMessageDialog(null,"Error, actualmente no existen facultades registrados","Mensaje",JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int valorIDEdificio = combobox.getId();
        
            int valorNivel = Integer.parseInt(nivel);
           
            
            String consulta = "CALL sp_agregarAulas(?,?,?)";
            
            Object[] params= {nombreSalon,valorIDEdificio,valorNivel};
            
            ResultSet ejecutar = Conexion.getInstancia().hacerConsulta(consulta, params);
            
            try{
                if (ejecutar!=null){

                    while(ejecutar.next()){
                        String mensajeObtenido = ejecutar.getString("mensaje");
  
                        
                        if(mensajeObtenido.equals("salonexiste")){
                            
                            JOptionPane.showMessageDialog(null, "Error, nombre de carrera en uso.","Mensaje",JOptionPane.ERROR_MESSAGE);   
                            
                        }else if(mensajeObtenido.equals("registrado")){
                            JOptionPane.showMessageDialog(null, "Registro exitoso","Mensaje",JOptionPane.INFORMATION_MESSAGE);   
                            txtNombreSalon.setText("");
                            txtNivel.setText("");
                            
                        }else if (mensajeObtenido.equals("edificionoexiste")){
                            JOptionPane.showMessageDialog(null, "Error, el edificio no está registrado.","Mensaje",JOptionPane.ERROR_MESSAGE);   

                        }else{
                            
                        }
                    }
                }                
            }catch(Exception ex){
                ex.printStackTrace();
            }  
        }
        
        

            
            
            
            //ResultSet consulta = Conexion.getInstancia().hacerConsulta(sentencia,params);
            
            
        
        /*if (confirmarGuardar==JOptionPane.YES_OPTION){
            if (combobox==null){
                JOptionPane.showMessageDialog(null,"Error, actualmente no existen facultades registrados","Mensaje",JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int idEdificio = combobox.getId();
            
           
            
            String sentencia = "CALL sp_agregarAulas(?,?,?)";
            
            Object[] params= {nombreSalon,idEdificio,Integer.parseInt(nivel)};
            
            
            
            ResultSet consulta = Conexion.getInstancia().hacerConsulta(sentencia,params);
            
            System.out.println("estoy aquiiiii consulta: "+consulta );
            try{
                if (consulta!=null){

                    if(consulta.next()){
                        String mensajeObtenido = consulta.getString("mensaje");
                        
                        System.out.println("estoy aquiiiii: "+mensajeObtenido);
                        if(mensajeObtenido.equals("salonexiste")){
                            
                            JOptionPane.showMessageDialog(null, "Error, nombre de carrera en uso.","Mensaje",JOptionPane.ERROR_MESSAGE);   
                            
                        }else if(mensajeObtenido.equals("registrado")){
                            JOptionPane.showMessageDialog(null, "Registro exitoso","Mensaje",JOptionPane.INFORMATION_MESSAGE);   
                            txtNombreSalon.setText("");
                            txtNivel.setText("");
                        }else if(mensajeObtenido.equals("edificionoexiste")){

                            JOptionPane.showMessageDialog(null, "Error, edificio no existe.","Mensaje",JOptionPane.ERROR_MESSAGE);   

                        }else{
                            //return;
                        }
                    }
                }                
            }catch(Exception ex){
                ex.printStackTrace();
            }  
            
        }*/
            

        
    }//GEN-LAST:event_btnRegistrarAulasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarAulas;
    private javax.swing.JComboBox<String> cboEdificio;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JLabel lblEdificio;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblSalon;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNombreSalon;
    // End of variables declaration//GEN-END:variables
}
