/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package jinternal;

import db.Conexion;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author santoslopeztzoy
 */
public class RegistrarEdificio extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarEdificio
     */
    public RegistrarEdificio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreEdificio = new javax.swing.JTextField();
        btnRegistrarEdificio = new javax.swing.JToggleButton();

        setClosable(true);
        setTitle("Registrar edificios");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar edificio");

        jLabel2.setText("Nombre edificio");

        btnRegistrarEdificio.setText("Guardar");
        btnRegistrarEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEdificioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(txtNombreEdificio)
            .addComponent(btnRegistrarEdificio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEdificioActionPerformed
        // TODO add your handling code here:
        
        
        String nombreEdificio = txtNombreEdificio.getText();
        
        int longitudNombreEdificio = nombreEdificio.length();
        
                
        if (longitudNombreEdificio<=0){
            
            JOptionPane.showMessageDialog(null, "Error, debes ingresar un nombre de edificio","Mensaje",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        int confirmar = JOptionPane.showConfirmDialog(null,"¿Deseas guardar los datos?","Mensaje",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if (confirmar==JOptionPane.YES_OPTION){
            
            String consulta = "CALL sp_agregarEdificio(?)";
            
            Object[] params = {nombreEdificio};
            
            ResultSet res = Conexion.getInstancia().hacerConsulta(consulta, params);
            
            try{
                if (res!=null){
                    
                    if(res.next()){
                        String mensajeObtenido = res.getString("mensaje");
                        
                        if (mensajeObtenido.equals("yaexiste")){
                            JOptionPane.showMessageDialog(null, "Error, edificio ya existe.","Mensaje",JOptionPane.ERROR_MESSAGE);
                        }else if (mensajeObtenido.equals("registrado")){
                            JOptionPane.showMessageDialog(null, "El edificio fue registrado.","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                            
                            txtNombreEdificio.setText("");
                            
                            ListadoEdificios.getInstancia().getModelo().actualizarJTable();
                            
                        }else if (mensajeObtenido.equals("errorproducido")){
                            JOptionPane.showMessageDialog(null, "Error producido.","Mensaje",JOptionPane.ERROR_MESSAGE);
  
                        }else{
                                
                        }
                    }
                }
            }catch(Exception ex){
                ex.printStackTrace();
            }
        }
        
        
    }//GEN-LAST:event_btnRegistrarEdificioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnRegistrarEdificio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JTextField txtNombreEdificio;
    // End of variables declaration//GEN-END:variables
}
